export const tracks = [
  { id: 1, title: "Flawless (Remix)", artist: "Beyoncé ft. Nicki Minaj", cover: "/images/image.png", src: "/audio/Flawless(remix)- Beyonce ft Niki Minaj.mp3" },
  { id: 2, title: "I Wanna Be Yours", artist: "Arctic Monkeys", cover: "/images/image.png", src: "/audio/Arctic Monkeys - I Wanna Be Yours.mp3" },
  { id: 3, title: "Dangerous Woman", artist: "Ariana Grande", cover: "/images/image.png", src: "/audio/Ariana Grande - Dangerous Woman (Lyrics).mp3" },
  { id: 4, title: "No Tears Left To Cry", artist: "Ariana Grande", cover: "/images/image.png", src: "/audio/Ariana Grande - No Tears Left To Cry (Lyrics).mp3" },
  { id: 5, title: "Dangerously In Love", artist: "Beyoncé", cover: "/images/image.png", src: "/audio/Beyonce - Dangerously In Love (Lyrics).mp3" },
  { id: 6, title: "Lovely", artist: "Billie Eilish ft. Khalid", cover: "/images/image.png", src: "/audio/Billie Eilish - lovely (Lyrics) ft. Khalid.mp3" },
  { id: 7, title: "How Deep Is Your Love", artist: "Calvin Harris & Disciples", cover: "/images/image.png", src: "/audio/Calvin Harris & Disciples - How Deep Is Your Love (Lyrics).mp3" },
  { id: 8, title: "Shameless", artist: "Camila Cabello", cover: "/images/image.png", src: "/audio/Camila Cabello - Shameless.mp3" },
  { id: 9, title: "Can't Feel My Face", artist: "The Weeknd", cover: "/images/image.png", src: "/audio/Can't Feel My Face - The Weeknd (Lyrics).mp3" },
  { id: 10, title: "Like A Boy", artist: "Ciara", cover: "/images/image.png", src: "/audio/Ciara - Like A Boy (Lyrics).mp3" },
  { id: 11, title: "Crazy In Love", artist: "Beyoncé ft. Jay Z", cover: "/images/image.png", src: "/audio/Crazy In Love - Beyonce (Feat. Jay Z) (Lyrics).mp3" },
  { id: 12, title: "Desperado", artist: "Rihanna", cover: "/images/image.png", src: "/audio/Desperado  - Rihanna.mp3" },
  { id: 13, title: "Flames", artist: "Donzell Taggart", cover: "/images/image.png", src: "/audio/Donzell Taggart - Flames (Lyrics).mp3" },
  { id: 14, title: "Drunk In Love", artist: "Beyoncé ft. Jay Z", cover: "/images/image.png", src: "/audio/Drunk In Love - Beyonce (Feat. Jay Z) (Lyrics).mp3" },
  { id: 15, title: "Don't Surrender", artist: "Egzod & EMM", cover: "/images/image.png", src: "/audio/Egzod & EMM - Don't Surrender [Official Lyric Video].mp3" },
  { id: 16, title: "Bring Me To Life", artist: "Evanescence", cover: "/images/image.png", src: "/audio/Evanescence - Bring Me To Life.mp3" },
  { id: 17, title: "Fade Away", artist: "Romain Virgo ft. Agent Sasco", cover: "/images/image.png", src: "/audio/Fade Away - Romain Virgo ft. Agent Sasco .mp3" },
  { id: 18, title: "Spectrum", artist: "Florence + The Machine", cover: "/images/image.png", src: "/audio/Florence + The Machine - Spectrum (Lyrics).mp3" },
  { id: 19, title: "Infinity", artist: "Jaymes Young", cover: "/images/image.png", src: "/audio/Jaymes Young - Infinity.mp3" },
  { id: 20, title: "Think Like A Man", artist: "Jennifer Hudson ft. Ne-Yo & Rick Ross", cover: "/images/image.png", src: "/audio/Jennifer Hudson Ft. Ne-Yo & Rick Ross- Think Like A Man.mp3" },
  { id: 21, title: "Good Enough", artist: "Jussie Smollett", cover: "/images/image.png", src: "/audio/Jussie Smollett - Good Enough (Lyrics).mp3" },
  { id: 22, title: "Cry Me A River", artist: "Justin Timberlake", cover: "/images/image.png", src: "/audio/Justin Timberlake - Cry Me a River (Lyrics).mp3" },
  { id: 23, title: "Collide", artist: "Justine Skye ft. Tyga", cover: "/images/image.png", src: "/audio/Justine Skye - Collide ft. Tyga.mp3" },
  { id: 24, title: "V.S.O.P", artist: "K. Michelle", cover: "/images/image.png", src: "/audio/K.Michelle- VSOP lyrics.mp3" },
  { id: 25, title: "Knock You Down", artist: "Keri Hilson ft. Kanye West, Ne-Yo", cover: "/images/image.png", src: "/audio/Keri Hilson - Knock You Down (Lyrics) ft. Kanye West, Ne-Yo.mp3" },
  { id: 26, title: "Walk", artist: "Kwabs", cover: "/images/image.png", src: "/audio/Kwabs - Walk [Lyrics].mp3" },
  { id: 27, title: "People", artist: "Libianca", cover: "/images/image.png", src: "/audio/Libianca - People (Lyrics).mp3" },
  { id: 28, title: "Mirror", artist: "Lil Wayne ft. Bruno Mars", cover: "/images/image.png", src: "/audio/Lil Wayne feat. Bruno Mars - Mirror (Lyrics).mp3" },
  { id: 29, title: "Bout Mine", artist: "Mariah the Scientist", cover: "/images/image.png", src: "/audio/Mariah the Scientist - Bout Mine.mp3" },
  { id: 30, title: "Revenge", artist: "Mariah the Scientist", cover: "/images/image.png", src: "/audio/Mariah the Scientist - Revenge .mp3" },
  { id: 31, title: "Cold", artist: "Maroon 5 ft. Future", cover: "/images/image.png", src: "/audio/Maroon 5 - Cold (Lyrics) ft. Future.mp3" },
  { id: 32, title: "Ruined Me", artist: "Muni Long", cover: "/images/image.png", src: "/audio/Muni Long - Ruined Me .mp3" },
  { id: 33, title: "So Far So Fake", artist: "Pierce The Veil", cover: "/images/image.png", src: "/audio/Pierce The Veil - So Far So Fake.mp3" },
  { id: 34, title: "Silence", artist: "Popcaan", cover: "/images/image.png", src: "/audio/Popcaan - Silence .mp3" },
  { id: 35, title: "Escapism", artist: "RAYE ft. 070 Shake", cover: "/images/image.png", src: "/audio/RAYE - Escapism. feat. 070 Shake.mp3" },
  { id: 36, title: "Oscar Winning Tears", artist: "RAYE", cover: "/images/image.png", src: "/audio/RAYE - Oscar Winning Tears.mp3" },
  { id: 37, title: "Russian Roulette", artist: "Rihanna", cover: "/images/image.png", src: "/audio/Rihanna - Russian Roulette.mp3" },
  { id: 38, title: "Unfaithful", artist: "Rihanna", cover: "/images/image.png", src: "/audio/Rihanna - Unfaithful.mp3" },
  { id: 39, title: "Breakin' Dishes", artist: "Rihanna", cover: "/images/image.png", src: "/audio/Rihanna Breakin' Dishes.mp3" },
  { id: 40, title: "Too Good At Goodbyes", artist: "Sam Smith", cover: "/images/image.png", src: "/audio/Sam Smith - Too Good At Goodbyes .mp3" },
  { id: 41, title: "Fetish", artist: "Selena Gomez ft. Gucci Mane", cover: "/images/image.png", src: "/audio/Selena Gomez - Fetish  ft. Gucci Mane.mp3" },
  { id: 42, title: "Love You Like A Love Song", artist: "Selena Gomez", cover: "/images/image.png", src: "/audio/Selena Gomez - Love You Like a Love Song.mp3" },
  { id: 43, title: "Same Old Love", artist: "Selena Gomez", cover: "/images/image.png", src: "/audio/Selena Gomez - Same Old Love .mp3" },
  { id: 44, title: "Take Me Back To Eden", artist: "Sleep Token", cover: "/images/image.png", src: "/audio/Sleep Token - Take Me Back To Eden .mp3" },
  { id: 45, title: "Lose Control", artist: "Teddy Swims", cover: "/images/image.png", src: "/audio/Teddy Swims - Lose Control .mp3" },
  { id: 46, title: "Sweater Weather", artist: "The Neighbourhood", cover: "/images/image.png", src: "/audio/The Neighbourhood - Sweater Weather .mp3" },
  { id: 47, title: "The Hills", artist: "The Weeknd", cover: "/images/image.png", src: "/audio/The Weeknd - The Hills .mp3" },
  { id: 48, title: "Apologize", artist: "Timbaland", cover: "/images/image.png", src: "/audio/Timbaland - Apologize .mp3" },
  { id: 49, title: "Towards The Sun", artist: "Rihanna", cover: "/images/image.png", src: "/audio/Towards The Sun - Rihanna.mp3" },
  { id: 50, title: "Love You Like Me", artist: "William Singe", cover: "/images/image.png", src: "/audio/William Singe - Love You Like Me.mp3" },
];